#!/usr/bin/perl -w

#----------------------------------------------------------------------
# Copyright 1999-2003 Mitel Networks Corporation
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#----------------------------------------------------------------------

exec "/sbin/e-smith/db", "configuration", @ARGV;
die "Could not exec /sbin/e-smith/db";
