#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Event;
use Data::Dumper;

my $usage = "NethServer (C) 2012 Nethesis srl

Usage:
    $0 <command>
    
    <command> := add|enable|disable|list|signal|status

    Command description:

	add	: if queue is enabled, add an event to it
	enable  : create an empty queue and enable it
	disable : disable and remove the queue contents
	list    : show the current event queue contents
	signal  : signal the events in the queue and disable it
	status  : check if the queue is enabled or not

";

my ($cmd, @args) = @ARGV;
my $returnValue = 0;

if($cmd eq 'enable') {
    $returnValue = NethServer::Event::queue_initialize();

} elsif($cmd eq 'disable') {
    $returnValue = NethServer::Event::queue_flush();

} elsif($cmd eq 'signal') {
    $returnValue = NethServer::Event::queue_signal();

} elsif($cmd eq 'status') {
    $returnValue = NethServer::Event::queue_is_enabled();

} elsif($cmd eq 'list') {
    if(NethServer::Event::queue_is_enabled()) {
	foreach(@{NethServer::Event::queue_read()}) {
	    print join("\t", @{$_}) . "\n";
	}
	$returnValue = 1;
    } else {
	$returnValue = 0;
    }
} elsif($cmd eq 'add') {
    if (NethServer::Event::queue_is_enabled()) {
       NethServer::Event::queue_add(@args);
    }
    $returnValue = 1;

} else {
    die $usage;

}

exit($returnValue > 0 ? 0 : 1);
