#!/usr/bin/perl -w

#----------------------------------------------------------------------
# Copyright 1999-2003 Mitel Networks Corporation
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#----------------------------------------------------------------------

use strict;
use esmith::event;
use Env qw(LANG LANGUAGE);

my $json = 0;

my $usage = "usage:
    $0 [-j|--json] <eventname> [arg1 [arg2...]]
";

if(defined $ARGV[0] && ($ARGV[0] eq '-j' || $ARGV[0] eq '--json')) {
    $json = 1;
    shift @ARGV;
}
my ($event, @args) = @ARGV;
die $usage unless $event;

#
# Reset locale settings - see man setlocale(3) - Refs #973
#
$LANG='en_US.utf8';
delete $ENV{LANGUAGE};
delete $ENV{$_} foreach grep(m/^LC_.+/, keys %ENV);

set_json_log($json);
my $exitcode = event_signal($event, @args);


# reverse exitcode for command-line usage
exit ($exitcode ? 0 : 1);

