#!/usr/bin/perl -w

#----------------------------------------------------------------------
# Copyright 2011 Nethesis - www.nethesis.it
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#----------------------------------------------------------------------

use strict;
use Getopt::Long;
use esmith::validator;

my $usage = "usage:
    $0 validatorname [arg1 [arg2...]]
";

my ($validator, @args) = @ARGV;
die $usage unless $validator;

my $exitcode = validate($validator, @args);

exit ($exitcode);

