#!/usr/bin/python

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

import nethserver.ptrack
import logging            
import os
import sys
import signal
import json
import io
import hashlib

if __name__ == "__main__":
    if("PTRACK_DEBUG" in os.environ):
        logging.getLogger().setLevel(logging.DEBUG)        

    if("PTRACK_SOCKETPATH" in os.environ):
        socket_path = os.environ["PTRACK_SOCKETPATH"]
    else:
        socket_path = os.environ["PTRACK_SOCKETPATH"] \
                      = '/var/run/ptrack-%d.sock' % os.getpid()

    state = nethserver.ptrack.ProgressState()
    server = nethserver.ptrack.TrackerServer(socket_path, state, True)
    exit_code = 0

    def on_sigchld(signum, frame):
        global exit_code
        logging.debug("Received signal: %d" % signum)
        exit_code = os.WEXITSTATUS(os.wait()[1])
        logging.debug("Child exit code: %d" % exit_code)
        server.close()

    def dump():
        global exit_code
        oldmask = os.umask(0077)
        dumpfd = io.open('/var/spool/ptrack/%.16s.dump' % hashlib.md5(socket_path).hexdigest(), 'wb')
        json.dump({'exit_code': exit_code, 'progress': state.query('progress'), 'tasks': state.query('tasks')}, dumpfd); 
        dumpfd.close()
        os.umask(oldmask)

    signal.signal(signal.SIGCHLD, on_sigchld)

    if(len(sys.argv) < 2):
        sys.stderr.write("Listening on path %s\nType ^C to shutdown the server.\n" % socket_path)
        try:
            server.loop()
        except KeyboardInterrupt:
            sys.stderr.write("\nInterrupted!\n")
            exit(0)        

    if(os.fork()):
        server.loop()
        dump()
        exit(exit_code)
    else:
        server.close()
        logging.debug("Spawning %s" % sys.argv)
        try:
            os.execv(sys.argv[1], sys.argv[1:])
        except Exception, e:
            sys.stderr.write("%s: %s\n" % (sys.argv[1], e))
            sys.exit(1)

